name: smart-iiot
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.5.1
  - xgboost=2.1.1
  - matplotlib
  - seaborn=0.13.2
  - joblib=1.4.2
  - imbalanced-learn=0.12.3
  - pip
  - pip:
    - fastapi==0.115.0
    - uvicorn==0.30.1
    - pydantic==2.8.2
    - python-dotenv==1.0.1
    - requests==2.32.3
    - streamlit==1.37.1
    - plotly==5.23.0
    - mlflow==2.14.1
    - pytest==8.3.2
    - black==24.10.0
    - flake8==7.1.1
    - isort==5.13.2
    - bandit==1.7.9
    - pre-commit==3.8.0
    - jupyterlab==4.2.4